# Generated by Django 4.0 on 2022-02-21 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_business_fecha_ultimo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Destacado - Mes pagado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaUltimoPago',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Fecha Ultimo Pago'),
        ),
    ]
